SELECT ML1.GENDER,CT,TOTAL, (CT*100/TOTAL) PERC FROM 
(SELECT GENDER, COUNT(*) CT
FROM PROJECT8.DBO.[IBM HR DATASET]   ---------- PARAM
WHERE ATTRITION=1 AND GENDER='MALE'
GROUP BY GENDER ) ML1
INNER JOIN
(SELECT GENDER, COUNT(*) TOTAL
FROM PROJECT8.DBO.[IBM HR DATASET]
WHERE  GENDER='MALE'
GROUP BY GENDER) MLT
ON MLT.GENDER=ML1.GENDER

UNION ALL

SELECT FL1.GENDER,CT,TOTAL, (CT*100/TOTAL) PERC FROM 
(SELECT GENDER, COUNT(*) CT
FROM PROJECT8.DBO.[IBM HR DATASET]   ---------- PARAM
WHERE ATTRITION=1 AND GENDER='FEMALE'
GROUP BY GENDER ) FL1
INNER JOIN
(SELECT GENDER, COUNT(*) TOTAL
FROM PROJECT8.DBO.[IBM HR DATASET]
WHERE  GENDER='FEMALE'
GROUP BY GENDER) FLT
ON FLT.GENDER=FL1.GENDER

---------------------------------------------------------------------------------------------------------------------------------

SELECT JB1.JOBROLE,CT,TOTAL,(CT*100/TOTAL) PERC FROM 
(SELECT JOBROLE, COUNT(*) CT
FROM PROJECT8.DBO.[IBM HR DATASET]  ----------CRUCIAL PARAM
WHERE ATTRITION=1 
GROUP BY JOBROLE
) JB1

INNER JOIN
(
SELECT JOBROLE, COUNT(*) TOTAL
FROM PROJECT8.DBO.[IBM HR DATASET] 
GROUP BY JOBROLE

) JBT
ON JB1.JOBROLE=JBT.JOBROLE

-------------------------------------------------------------------------------------------------------------------------------------

SELECT MS1.MARITALSTATUS,CT,TOTAL,(CT*100/TOTAL) PERC
FROM
(
SELECT MARITALSTATUS,COUNT(*) CT 
FROM PROJECT8.DBO.[IBM HR DATASET]
WHERE ATTRITION=1
GROUP BY MARITALSTATUS
) MS1
INNER JOIN
(
SELECT MARITALSTATUS,COUNT(*) TOTAL ----------CRUCIAL PARAM
FROM PROJECT8.DBO.[IBM HR DATASET]
GROUP BY MARITALSTATUS
) MST
ON
MS1.MARITALSTATUS=MST.MARITALSTATUS

--------------------------------------------------------------------------------------------------------------------------------------

SELECT T1.DEPARTMENT,CT,TOTAL,(CT*100/TOTAL) PERC FROM
(SELECT DEPARTMENT, COUNT(*) TOTAL
FROM PROJECT8.DBO.[IBM HR DATASET]

GROUP BY DEPARTMENT ) T1
INNER JOIN 
(SELECT DEPARTMENT, COUNT(*) CT
FROM PROJECT8.DBO.[IBM HR DATASET]------------PARAM
WHERE ATTRITION=1
GROUP BY DEPARTMENT ) T2
ON T1.DEPARTMENT=T2.DEPARTMENT

--------------------------------------------------------------------------------------------------------------------------------------
SELECT AGEGROUP, SUM(CT)
FROM
(
SELECT CASE WHEN T1.AGE>17 AND T1.AGE<27 THEN '18-26'
     WHEN T1.AGE>26 AND T1.AGE<32 THEN '27-31'
     WHEN T1.AGE>31 THEN '31+'
     END AGEGROUP,CT
     FROM
(SELECT AGE, COUNT(*) CT
FROM PROJECT8.DBO.[IBM HR DATASET] -------------CRUCIAL PARAM
WHERE ATTRITION=1
GROUP BY AGE
) T1
)TT1
GROUP  BY AGEGROUP

-----------------------------------------------------------------------------------------------------------------------------------------

SELECT T1.BUSINESSTRAVEL,ct,total,(CT*100/TOTAL) perc FROM
(SELECT BUSINESSTRAVEL,COUNT(*) Total
FROM PROJECT8.DBO.[IBM HR DATASET]
GROUP BY BUSINESSTRAVEL)T1
INNER JOIN 
(SELECT BUSINESSTRAVEL,COUNT(*) CT 
FROM PROJECT8.DBO.[IBM HR DATASET]  -------------CRUCIAL PARAM
WHERE ATTRITION=1
GROUP BY BUSINESSTRAVEL)T2
ON T1.BUSINESSTRAVEL=T2.BUSINESSTRAVEL


--------------------------------------------------------------------------------------------------------------------------------------


SELECT tt1.CATEGORY,Ct,Total, (CT*100/TOTAL) perc FROM
(SELECT CATEGORY,COUNT(*) Total FROM
(
SELECT 
CASE WHEN MONTHLYINCOME>10000 THEN 'HIGH'
     WHEN MONTHLYINCOME>5000 THEN 'MID'
      WHEN MONTHLYINCOME<5000 THEN 'LOW'
      END CATEGORY,*
FROM PROJECT8.DBO.[IBM HR DATASET]
) T1
GROUP BY CATEGORY) TT1
INNER JOIN                                    
(SELECT CATEGORY,COUNT(*) CT FROM
(
SELECT 
CASE WHEN MONTHLYINCOME>10000 THEN 'HIGH'
     WHEN MONTHLYINCOME>5000 THEN 'MID'
      WHEN MONTHLYINCOME<5000 THEN 'LOW'
      END CATEGORY,*
FROM PROJECT8.DBO.[IBM HR DATASET]
WHERE ATTRITION=1) T1
GROUP BY CATEGORY)TT2
ON TT1.CATEGORY= TT2.CATEGORY                 -------------crucial param


--------------------------------------------------------------------------------------------------------------------------------------


SELECT TBB1.EXPCAT,CT,TOTAL,(CT*100/TOTAL) PERC FROM
(SELECT EXPCAT, COUNT(*) CT FROM 
(SELECT CASE WHEN YEARSATCOMPANY>10 THEN 'LOYAL EMPLYOYEE'
            WHEN YEARSATCOMPANY>5 THEN 'SETTLED EMPLOYEES'
            WHEN YEARSATCOMPANY<=5 THEN 'NEW EMPLOYEES' END EXPCAT
            ,*

FROM PROJECT8.DBO.[IBM HR DATASET]
WHERE ATTRITION=1) TB1
GROUP BY EXPCAT) TBB1
INNER JOIN
(SELECT EXPCAT, COUNT(*) TOTAL FROM 
(SELECT CASE WHEN YEARSATCOMPANY>10 THEN 'LOYAL EMPLYOYEE'
            WHEN YEARSATCOMPANY>5 THEN 'SETTLED EMPLOYEES'
            WHEN YEARSATCOMPANY<=5 THEN 'NEW EMPLOYEES' END EXPCAT
            ,*

FROM PROJECT8.DBO.[IBM HR DATASET]
) TB2
GROUP BY EXPCAT) TBB2
ON TBB1.EXPCAT=TBB2.EXPCAT ---------------crecial param

--------------------------------------------------------------------------------------------------------------------------------------


SELECT TBB1.TEXPCAT,CT,TOTAL,(CT*100/TOTAL) PERC FROM
(SELECT TEXPCAT, COUNT(*) CT FROM 
(SELECT CASE WHEN TOTALWORKINGYEARS<5 THEN 'JUNIORS'
            WHEN 5<=TOTALWORKINGYEARS AND TOTALWORKINGYEARS <10 THEN 'MID LEVEL'
            WHEN TOTALWORKINGYEARS>=10 THEN 'SENIORS' END TEXPCAT
            ,*

FROM PROJECT8.DBO.[IBM HR DATASET]
WHERE ATTRITION=1) TB1
GROUP BY TEXPCAT) TBB1
INNER JOIN
(SELECT TEXPCAT, COUNT(*) TOTAL FROM 
(SELECT CASE WHEN TOTALWORKINGYEARS<5 THEN 'JUNIORS'
            WHEN 5<=TOTALWORKINGYEARS AND TOTALWORKINGYEARS <10 THEN 'MID LEVEL'
            WHEN TOTALWORKINGYEARS>=10 THEN 'SENIORS' END TEXPCAT
            ,*

FROM PROJECT8.DBO.[IBM HR DATASET]
) TB2
GROUP BY TEXPCAT) TBB2
ON TBB1.TEXPCAT=TBB2.TEXPCAT  -----------CRUCIAL PARAM


--------------------------------------------------------------------------------------------------------------------------------------

SELECT YEARSINCURRENTROLE, COUNT(*) FROM PROJECT8.DBO.[IBM HR DATASET] ---------------CRUCIAL PARAM
WHERE  ATTRITION=1
GROUP BY YEARSINCURRENTROLE

--------------------------------------------------------------------------------------------------------------------------------------


SELECT T1.YEARSSINCELASTPROMOTION,CT,TOTAL,(CT*100/TOTAL) PERC
FROM
(SELECT YEARSSINCELASTPROMOTION, COUNT(*) CT FROM PROJECT8.DBO.[IBM HR DATASET] 
WHERE  ATTRITION=1                          ---------------CRUCIAL PARAM
GROUP BY YEARSSINCELASTPROMOTION) T1
INNER JOIN
(SELECT YEARSSINCELASTPROMOTION, COUNT(*) TOTAL  FROM PROJECT8.DBO.[IBM HR DATASET]                     
GROUP BY YEARSSINCELASTPROMOTION) T2
ON T1.YEARSSINCELASTPROMOTION=T2.YEARSSINCELASTPROMOTION

--------------------------------------------------------------------------------------------------------------------------------------


/* parameters affecting attrition

age
business travel
department
education Field
gender
job role
job satisfaction
marital status
monthly income
number of times company switched
percent salary hike
*/
--------------------------------------------------------------------------------------------------------------------------------------


SELECT T1.EDUCATIONFIELD,CT,TOTAL,(CT*100/TOTAL) PERC FROM
(
SELECT EDUCATIONFIELD, COUNT(*) TOTAL  FROM PROJECT8.DBO.[IBM HR DATASET]
GROUP BY EDUCATIONFIELD
)T1
INNER JOIN
(SELECT EDUCATIONFIELD, COUNT(*) CT FROM PROJECT8.DBO.[IBM HR DATASET]
WHERE ATTRITION=1
GROUP BY EDUCATIONFIELD)T2
ON T1.EDUCATIONFIELD=T2.EDUCATIONFIELD


--------------------------------------------------------------------------------------------------------------------------------------
SELECT T1.NUMCUM,CT,TOTAL,(CT*100/TOTAL) PERC FROM
(
SELECT NUMCUM, COUNT(*) TOTAL FROM
(SELECT 
CASE WHEN NUMCOMPANIESWORKED>6 THEN 'TOO MANY SWITCHES'
     WHEN 1<NUMCOMPANIESWORKED AND NUMCOMPANIESWORKED<=5 THEN 'MID NUMBER OF SWITCHES'
     ELSE 'FIRST COMPANY'
     END NUMCUM,
* FROM PROJECT8.DBO.[IBM HR DATASET]) TB
GROUP BY NUMCUM


)T1
INNER JOIN 
(
SELECT NUMCUM, COUNT(*) CT FROM

(SELECT 
CASE WHEN NUMCOMPANIESWORKED>6 THEN 'TOO MANY SWITCHES'
     WHEN 1<NUMCOMPANIESWORKED AND NUMCOMPANIESWORKED<=5 THEN 'MID NUMBER OF SWITCHES'
     ELSE 'FIRST COMPANY'
     END NUMCUM,
* FROM PROJECT8.DBO.[IBM HR DATASET]) TB
WHERE ATTRITION=1
GROUP BY NUMCUM
---------------CRUCIAL PARAM
)T2
ON T1.NUMCUM=T2.NUMCUM

select * from PROJECT8.dbo.[IBM HR Dataset]


